-- 1. Crear la tabla de contenido
create table content (
  id bigint generated by default as identity primary key,
  section text unique not null,
  data jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad (RLS)
alter table content enable row level security;

-- 3. Crear política para que TODOS puedan LEER (público)
create policy "Public content is viewable by everyone"
  on content for select
  using (true);

-- 4. Crear política para que TODOS puedan EDITAR (para simplificar, ya que tienes login en el admin)
-- NOTA: En un entorno más estricto, usaríamos autenticación de Supabase, 
-- pero esto permite que tu panel de admin funcione con la clave que ya tienes.
create policy "Enable update for all"
  on content for update
  using (true)
  with check (true);

create policy "Enable insert for all"
  on content for insert
  with check (true);

-- 5. Insertar datos iniciales (Estructura base)
insert into content (section, data)
values 
  ('home', '{
    "title": "CARTELERA ISMUNT - A. De Boeck",
    "subtitle": "Cartelera - Blog informativo",
    "generalInfo": "El acceso a las diapositivas de clase quedará restringido para todas las asignaturas, a excepción de contrapunto tonal, desde el día 2/7/2025.",
    "notices": []
  }'),
  ('materias', '{
    "tecnicas": { "id": "tecnicas", "name": "Técnicas compositivas desde el Siglo XX", "content": "", "resources": [] },
    "lectura": { "id": "lectura", "name": "Lectura e interpretación de la Música Contemporánea", "content": "", "resources": [] },
    "contrapunto": { "id": "contrapunto", "name": "Contrapunto Tonal", "content": "", "resources": [] },
    "historia2": { "id": "historia2", "name": "Historia de la Música II", "content": "", "resources": [] },
    "historia3": { "id": "historia3", "name": "Historia de la Música III", "content": "", "resources": [] }
  }');
